# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='homeworld',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
